apiVersion: v1
kind: ConfigMap
metadata:
  name: taskhub-config
  namespace: taskhub
data:
  ENVIRONMENT: production
  LOG_JSON: "true"
  DATABASE_HOST: postgres
  CORS_ORIGINS: '["http://localhost:3000"]'
  POSTGRES_DB: taskhub
  POSTGRES_USER: taskhub

